# Generated by Django 4.1.13 on 2024-04-01 08:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название категории')),
            ],
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.CharField(max_length=500, verbose_name='URL изображения')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Цена')),
                ('is_realted_price', models.IntegerField(blank=True, verbose_name='Цена')),
                ('author_name', models.CharField(max_length=50, verbose_name='Автор')),
                ('author_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('posted_date', models.DateTimeField(default=datetime.datetime(2024, 4, 1, 13, 14, 54, 875252), verbose_name='Дата и время публикации')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notice_app.category', verbose_name='Категория')),
            ],
        ),
    ]
